Rails.application.config.assets.precompile += %w( tablecloth.css )
Rails.application.config.assets.precompile += %w( prettify.css )
Rails.application.config.assets.precompile += %w( jquery.metadata.js )
Rails.application.config.assets.precompile += %w( jquery.tablesorter.js )
Rails.application.config.assets.precompile += %w( jquery.tablecloth.js )
Rails.application.config.assets.precompile += %w( html5shiv-printshiv.js )
Rails.application.config.assets.precompile += %w( html5shiv.js )
Rails.application.config.assets.precompile += %w( respond.min.js )
